export default {
  STATE_REQUEST_MESSAGE: 'Request for video state.', // SYNC WITH MainWebsocketServer.java
  POPUP_OPEN_EVENT: 'POPUP_OPEN_EVENT',
  POPUP_CLOSE_EVENT: 'POPUP_CLOSE_EVENT',
  CONNECT_COMMAND: 'CONNECT_COMMAND',
  FIND_NEW_VIDEO_COMMAND: 'FIND_NEW_VIDEO_COMMAND',
  TIME_SEEK_EPSILON: 0.1,
};
