matrix:
  include:
    - language: elixir
      elixir: '1.4'
      otp_release: '20.0'
      before_install:
        - cd fjord
      before_script:
        - cd fjord
      script:
        - mix test

    - language: node_js
      node_js: '8.9.4'
      before_install:
        - cd client/chrome-extension
        - npm i -g npm@5.6.0
      install:
        - npm install
      before_script:
        - cd client/chrome-extension
      script:
        - npm run test
        - npm run integrationTest
