language: java
jdk:
  - oraclejdk8

addons:
  artifacts:
    bucket: $ARTIFACTS_BUCKET
    paths:
        - $(ls server/build/libs | tr "\n" ":")
    key: $ARTIFACTS_KEY
    secret: $ARTIFACTS_SECRET

script:
  - ./gradlew jar

