language: java
jdk:
  - oraclejdk8

addons:
  artifacts:
    bucket: $ARTIFACTS_BUCKET
    paths:
        - ./server/build/libs
    key: $ARTIFACTS_KEY
    secret: $ARTIFACTS_SECRET

script:
  - ./gradlew jar
